using UnfathomableMaze.Enums;
using UnfathomableMaze.Interfaces;

namespace UnfathomableMaze.Controllers;

/// <summary>
/// The controller for the maze, it generates the map and converts it to a char array to be displayed in the console.
/// </summary>
/// <param name="mapTilesGenerator">The generator for the maze map structure.</param>
public class MazeController(IMapTilesGenerator mapTilesGenerator)
{
    /// <summary>
    /// The map of the maze, generated by the given <see cref="IMapTilesGenerator"/>.
    /// </summary>
    public Tile[,] TileMap
    {
        get => (Tile[,])field.Clone();
    } = mapTilesGenerator.Generate();

    /// <summary>
    /// Checks whether the player can move north.
    /// </summary>
    /// <param name="map">The map to be checked against.</param>
    /// <param name="x">The X position.</param>
    /// <param name="y">The Y position.</param>
    /// <returns>Whether the player can move north.</returns>
    public bool ValidateNorth(Tile[,] map, int x, int y)
    {
        return y > 0 && map[y - 1, x] == Tile.Wall;
    }

    /// <summary>
    /// Checks whether the player can move east.
    /// </summary>
    /// <param name="map">The map to be checked against.</param>
    /// <param name="x">The X position.</param>
    /// <param name="y">The Y position.</param>
    /// <returns>Whether the player can move east.</returns>
    public bool ValidateEast(Tile[,] map, int x, int y)
    {
        return x < map.GetLength(1) - 1 && map[y, x + 1] == Tile.Wall;
    }

    /// <summary>
    /// Checks whether the player can move south.
    /// </summary>
    /// <param name="map">The map to be checked against.</param>
    /// <param name="x">The X position.</param>
    /// <param name="y">The Y position.</param>
    /// <returns>Whether the player can move south.</returns>
    public bool ValidateSouth(Tile[,] map, int x, int y)
    {
        return y < map.GetLength(0) - 1 && map[y + 1, x] == Tile.Wall;
    }

    /// <summary>
    /// Checks whether the player can move west.
    /// </summary>
    /// <param name="map">The map to be checked against.</param>
    /// <param name="x">The X position.</param>
    /// <param name="y">The Y position.</param>
    /// <returns>Whether the player can move west.</returns>
    public bool ValidateWest(Tile[,] map, int x, int y)
    {
        return x > 0 && map[y, x - 1] == Tile.Wall;
    }
}
